CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `full_name` varchar(355) NOT NULL,
  `login` varchar(100) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(500) NOT NULL,
  `avatar` varchar(500) NOT NULL,
  `usercol` varchar(45) NOT NULL,
  `SBER` varchar(45) NOT NULL DEFAULT '0',
  `TINKOFF` varchar(45) NOT NULL DEFAULT '0',
  `VTB` varchar(45) NOT NULL DEFAULT '0',
  `ALPHA` varchar(45) NOT NULL DEFAULT '0',
  `GAZPROMBANK` varchar(45) NOT NULL DEFAULT '0',
  `MCB` varchar(45) NOT NULL DEFAULT '0',
  `SOVCOMBANK` varchar(45) NOT NULL DEFAULT '0',
  `OPENING` varchar(45) NOT NULL DEFAULT '0',
  `ROSSELKHOZBANK` varchar(45) NOT NULL DEFAULT '0',
  `RAIFFEISENBANK` varchar(45) NOT NULL DEFAULT '0',
  `ROSBANK` varchar(45) NOT NULL DEFAULT '0',
  `DOMRF` varchar(45) NOT NULL DEFAULT '0',
  `UNICREDIT` varchar(45) NOT NULL DEFAULT '0',
  `POSTBANK` varchar(45) NOT NULL DEFAULT '0',
  `AKBARS` varchar(45) NOT NULL DEFAULT '0',
  `BSPB` varchar(45) NOT NULL DEFAULT '0',
  `BANKRUSSIYA` varchar(45) NOT NULL DEFAULT '0',
  `URALSIB` varchar(45) NOT NULL DEFAULT '0',
  `MTS` varchar(45) NOT NULL DEFAULT '0',
  `NOVIKOMBANK` varchar(45) NOT NULL DEFAULT '0',
  `RNKB` varchar(45) NOT NULL DEFAULT '0',
  `GOLDKRONE` varchar(45) NOT NULL DEFAULT '0',
  `PROMSVYAZBANK` varchar(45) NOT NULL DEFAULT '0',
  `HOMEBANK` varchar(45) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`,`login`,`email`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1